plugins:
  - jekyll-relative-links  
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
markdown: kramdown
theme: jekyll-theme-cayman
title: DND Random Tables
description: [A short description of your site's purpose]

